AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 30
      Policies:
        - AWSLambdaExecute
      Events:
        MyScheduledFunctionTrigger:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Enabled: true